//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.11.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from D:/Projects/CSharp/PHPSharp/php-core/src/Core\PhpParser.g4 by ANTLR 4.11.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="PhpParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.11.1")]
[System.CLSCompliant(false)]
public interface IPhpParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.htmlDocument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHtmlDocument([NotNull] PhpParser.HtmlDocumentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.inlineHtml"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInlineHtml([NotNull] PhpParser.InlineHtmlContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.htmlElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHtmlElement([NotNull] PhpParser.HtmlElementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.scriptText"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitScriptText([NotNull] PhpParser.ScriptTextContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.phpBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPhpBlock([NotNull] PhpParser.PhpBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.importStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitImportStatement([NotNull] PhpParser.ImportStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.topStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTopStatement([NotNull] PhpParser.TopStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.useDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUseDeclaration([NotNull] PhpParser.UseDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.useDeclarationContentList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUseDeclarationContentList([NotNull] PhpParser.UseDeclarationContentListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.useDeclarationContent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUseDeclarationContent([NotNull] PhpParser.UseDeclarationContentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.namespaceDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamespaceDeclaration([NotNull] PhpParser.NamespaceDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.namespaceStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamespaceStatement([NotNull] PhpParser.NamespaceStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.functionDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionDeclaration([NotNull] PhpParser.FunctionDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.classDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassDeclaration([NotNull] PhpParser.ClassDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.classEntryType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassEntryType([NotNull] PhpParser.ClassEntryTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.interfaceList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterfaceList([NotNull] PhpParser.InterfaceListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.typeParameterListInBrackets"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeParameterListInBrackets([NotNull] PhpParser.TypeParameterListInBracketsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.typeParameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeParameterList([NotNull] PhpParser.TypeParameterListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.typeParameterWithDefaultsList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeParameterWithDefaultsList([NotNull] PhpParser.TypeParameterWithDefaultsListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.typeParameterDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeParameterDecl([NotNull] PhpParser.TypeParameterDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.typeParameterWithDefaultDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeParameterWithDefaultDecl([NotNull] PhpParser.TypeParameterWithDefaultDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.genericDynamicArgs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGenericDynamicArgs([NotNull] PhpParser.GenericDynamicArgsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.attributes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttributes([NotNull] PhpParser.AttributesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.attributeGroup"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttributeGroup([NotNull] PhpParser.AttributeGroupContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttribute([NotNull] PhpParser.AttributeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.innerStatementList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInnerStatementList([NotNull] PhpParser.InnerStatementListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.innerStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInnerStatement([NotNull] PhpParser.InnerStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] PhpParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.emptyStatement_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEmptyStatement_([NotNull] PhpParser.EmptyStatement_Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.blockStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlockStatement([NotNull] PhpParser.BlockStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfStatement([NotNull] PhpParser.IfStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.elseIfStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElseIfStatement([NotNull] PhpParser.ElseIfStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.elseIfColonStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElseIfColonStatement([NotNull] PhpParser.ElseIfColonStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.elseStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElseStatement([NotNull] PhpParser.ElseStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.elseColonStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElseColonStatement([NotNull] PhpParser.ElseColonStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.whileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhileStatement([NotNull] PhpParser.WhileStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.doWhileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDoWhileStatement([NotNull] PhpParser.DoWhileStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.forStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForStatement([NotNull] PhpParser.ForStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.forInit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForInit([NotNull] PhpParser.ForInitContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.forUpdate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForUpdate([NotNull] PhpParser.ForUpdateContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.switchStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSwitchStatement([NotNull] PhpParser.SwitchStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.switchBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSwitchBlock([NotNull] PhpParser.SwitchBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.breakStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBreakStatement([NotNull] PhpParser.BreakStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.continueStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitContinueStatement([NotNull] PhpParser.ContinueStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.returnStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturnStatement([NotNull] PhpParser.ReturnStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.expressionStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpressionStatement([NotNull] PhpParser.ExpressionStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.unsetStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnsetStatement([NotNull] PhpParser.UnsetStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.foreachStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForeachStatement([NotNull] PhpParser.ForeachStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.tryCatchFinally"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTryCatchFinally([NotNull] PhpParser.TryCatchFinallyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.catchClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCatchClause([NotNull] PhpParser.CatchClauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.finallyStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFinallyStatement([NotNull] PhpParser.FinallyStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.throwStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitThrowStatement([NotNull] PhpParser.ThrowStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.gotoStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGotoStatement([NotNull] PhpParser.GotoStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.declareStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclareStatement([NotNull] PhpParser.DeclareStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.inlineHtmlStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInlineHtmlStatement([NotNull] PhpParser.InlineHtmlStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.declareList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclareList([NotNull] PhpParser.DeclareListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.formalParameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFormalParameterList([NotNull] PhpParser.FormalParameterListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.formalParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFormalParameter([NotNull] PhpParser.FormalParameterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.typeHint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeHint([NotNull] PhpParser.TypeHintContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.globalStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGlobalStatement([NotNull] PhpParser.GlobalStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.globalVar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGlobalVar([NotNull] PhpParser.GlobalVarContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.echoStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEchoStatement([NotNull] PhpParser.EchoStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.staticVariableStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStaticVariableStatement([NotNull] PhpParser.StaticVariableStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.classStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassStatement([NotNull] PhpParser.ClassStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.traitAdaptations"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTraitAdaptations([NotNull] PhpParser.TraitAdaptationsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.traitAdaptationStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTraitAdaptationStatement([NotNull] PhpParser.TraitAdaptationStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.traitPrecedence"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTraitPrecedence([NotNull] PhpParser.TraitPrecedenceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.traitAlias"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTraitAlias([NotNull] PhpParser.TraitAliasContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.traitMethodReference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTraitMethodReference([NotNull] PhpParser.TraitMethodReferenceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.baseCtorCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBaseCtorCall([NotNull] PhpParser.BaseCtorCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.methodBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethodBody([NotNull] PhpParser.MethodBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.propertyModifiers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPropertyModifiers([NotNull] PhpParser.PropertyModifiersContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.memberModifiers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMemberModifiers([NotNull] PhpParser.MemberModifiersContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.variableInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableInitializer([NotNull] PhpParser.VariableInitializerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.identifierInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifierInitializer([NotNull] PhpParser.IdentifierInitializerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.globalConstantDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGlobalConstantDeclaration([NotNull] PhpParser.GlobalConstantDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.expressionList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpressionList([NotNull] PhpParser.ExpressionListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.parentheses"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParentheses([NotNull] PhpParser.ParenthesesContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ChainExpression</c>
	/// labeled alternative in <see cref="PhpParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitChainExpression([NotNull] PhpParser.ChainExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SpecialWordExpression</c>
	/// labeled alternative in <see cref="PhpParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSpecialWordExpression([NotNull] PhpParser.SpecialWordExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ArrayCreationExpression</c>
	/// labeled alternative in <see cref="PhpParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayCreationExpression([NotNull] PhpParser.ArrayCreationExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>BackQuoteStringExpression</c>
	/// labeled alternative in <see cref="PhpParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBackQuoteStringExpression([NotNull] PhpParser.BackQuoteStringExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>MatchExpression</c>
	/// labeled alternative in <see cref="PhpParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMatchExpression([NotNull] PhpParser.MatchExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LogicalExpression</c>
	/// labeled alternative in <see cref="PhpParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogicalExpression([NotNull] PhpParser.LogicalExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>PrintExpression</c>
	/// labeled alternative in <see cref="PhpParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrintExpression([NotNull] PhpParser.PrintExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>AssignmentExpression</c>
	/// labeled alternative in <see cref="PhpParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignmentExpression([NotNull] PhpParser.AssignmentExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>PostfixIncDecExpression</c>
	/// labeled alternative in <see cref="PhpParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPostfixIncDecExpression([NotNull] PhpParser.PostfixIncDecExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>CloneExpression</c>
	/// labeled alternative in <see cref="PhpParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCloneExpression([NotNull] PhpParser.CloneExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UnaryOperatorExpression</c>
	/// labeled alternative in <see cref="PhpParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnaryOperatorExpression([NotNull] PhpParser.UnaryOperatorExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NewExpression</c>
	/// labeled alternative in <see cref="PhpParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNewExpression([NotNull] PhpParser.NewExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ParenthesisExpression</c>
	/// labeled alternative in <see cref="PhpParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParenthesisExpression([NotNull] PhpParser.ParenthesisExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SpaceshipExpression</c>
	/// labeled alternative in <see cref="PhpParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSpaceshipExpression([NotNull] PhpParser.SpaceshipExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ConditionalExpression</c>
	/// labeled alternative in <see cref="PhpParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConditionalExpression([NotNull] PhpParser.ConditionalExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NullCoalescingExpression</c>
	/// labeled alternative in <see cref="PhpParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNullCoalescingExpression([NotNull] PhpParser.NullCoalescingExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ArithmeticExpression</c>
	/// labeled alternative in <see cref="PhpParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArithmeticExpression([NotNull] PhpParser.ArithmeticExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>IndexerExpression</c>
	/// labeled alternative in <see cref="PhpParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIndexerExpression([NotNull] PhpParser.IndexerExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ScalarExpression</c>
	/// labeled alternative in <see cref="PhpParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitScalarExpression([NotNull] PhpParser.ScalarExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>PrefixIncDecExpression</c>
	/// labeled alternative in <see cref="PhpParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrefixIncDecExpression([NotNull] PhpParser.PrefixIncDecExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ComparisonExpression</c>
	/// labeled alternative in <see cref="PhpParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComparisonExpression([NotNull] PhpParser.ComparisonExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>CastExpression</c>
	/// labeled alternative in <see cref="PhpParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCastExpression([NotNull] PhpParser.CastExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>InstanceOfExpression</c>
	/// labeled alternative in <see cref="PhpParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInstanceOfExpression([NotNull] PhpParser.InstanceOfExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LambdaFunctionExpression</c>
	/// labeled alternative in <see cref="PhpParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLambdaFunctionExpression([NotNull] PhpParser.LambdaFunctionExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>BitwiseExpression</c>
	/// labeled alternative in <see cref="PhpParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBitwiseExpression([NotNull] PhpParser.BitwiseExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.assignable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignable([NotNull] PhpParser.AssignableContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.arrayCreation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayCreation([NotNull] PhpParser.ArrayCreationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.lambdaFunctionExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLambdaFunctionExpr([NotNull] PhpParser.LambdaFunctionExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.matchExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMatchExpr([NotNull] PhpParser.MatchExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.matchItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMatchItem([NotNull] PhpParser.MatchItemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.newExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNewExpr([NotNull] PhpParser.NewExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.assignmentOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignmentOperator([NotNull] PhpParser.AssignmentOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.yieldExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitYieldExpression([NotNull] PhpParser.YieldExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.arrayItemList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayItemList([NotNull] PhpParser.ArrayItemListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.arrayItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayItem([NotNull] PhpParser.ArrayItemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.lambdaFunctionUseVars"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLambdaFunctionUseVars([NotNull] PhpParser.LambdaFunctionUseVarsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.lambdaFunctionUseVar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLambdaFunctionUseVar([NotNull] PhpParser.LambdaFunctionUseVarContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.qualifiedStaticTypeRef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQualifiedStaticTypeRef([NotNull] PhpParser.QualifiedStaticTypeRefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.typeRef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeRef([NotNull] PhpParser.TypeRefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.anonymousClass"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnonymousClass([NotNull] PhpParser.AnonymousClassContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.indirectTypeRef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIndirectTypeRef([NotNull] PhpParser.IndirectTypeRefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.qualifiedNamespaceName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQualifiedNamespaceName([NotNull] PhpParser.QualifiedNamespaceNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.namespaceNameList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamespaceNameList([NotNull] PhpParser.NamespaceNameListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.namespaceNameTail"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamespaceNameTail([NotNull] PhpParser.NamespaceNameTailContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.qualifiedNamespaceNameList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQualifiedNamespaceNameList([NotNull] PhpParser.QualifiedNamespaceNameListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.arguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArguments([NotNull] PhpParser.ArgumentsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.actualArgument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitActualArgument([NotNull] PhpParser.ActualArgumentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.argumentName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgumentName([NotNull] PhpParser.ArgumentNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.constantInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstantInitializer([NotNull] PhpParser.ConstantInitializerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.constant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstant([NotNull] PhpParser.ConstantContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.literalConstant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteralConstant([NotNull] PhpParser.LiteralConstantContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.numericConstant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumericConstant([NotNull] PhpParser.NumericConstantContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.classConstant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassConstant([NotNull] PhpParser.ClassConstantContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.stringConstant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStringConstant([NotNull] PhpParser.StringConstantContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitString([NotNull] PhpParser.StringContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.interpolatedStringPart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterpolatedStringPart([NotNull] PhpParser.InterpolatedStringPartContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.chainList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitChainList([NotNull] PhpParser.ChainListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.chain"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitChain([NotNull] PhpParser.ChainContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.chainOrigin"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitChainOrigin([NotNull] PhpParser.ChainOriginContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.memberAccess"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMemberAccess([NotNull] PhpParser.MemberAccessContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionCall([NotNull] PhpParser.FunctionCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.functionCallName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionCallName([NotNull] PhpParser.FunctionCallNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.actualArguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitActualArguments([NotNull] PhpParser.ActualArgumentsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.chainBase"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitChainBase([NotNull] PhpParser.ChainBaseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.keyedFieldName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitKeyedFieldName([NotNull] PhpParser.KeyedFieldNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.keyedSimpleFieldName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitKeyedSimpleFieldName([NotNull] PhpParser.KeyedSimpleFieldNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.keyedVariable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitKeyedVariable([NotNull] PhpParser.KeyedVariableContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.squareCurlyExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSquareCurlyExpression([NotNull] PhpParser.SquareCurlyExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.assignmentList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignmentList([NotNull] PhpParser.AssignmentListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.assignmentListElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignmentListElement([NotNull] PhpParser.AssignmentListElementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.modifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModifier([NotNull] PhpParser.ModifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifier([NotNull] PhpParser.IdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.memberModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMemberModifier([NotNull] PhpParser.MemberModifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.magicConstant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMagicConstant([NotNull] PhpParser.MagicConstantContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.magicMethod"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMagicMethod([NotNull] PhpParser.MagicMethodContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.primitiveType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimitiveType([NotNull] PhpParser.PrimitiveTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PhpParser.castOperation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCastOperation([NotNull] PhpParser.CastOperationContext context);
}
